name: "install-plugins"
description: "Install C2P Plugins"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: 'main'
        token: '${{ github.token }}'
        repository: "jpower432/c2p-opa-plugin"
        path: c2p

    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: '1.24'
        cache: false
        check-latest: true

    - name: Build
      working-directory: c2p
      run: go build -o ./bin/opa-plugin ./cmd/opa-plugin
      shell: bash

    - name: Add to path
      working-directory: c2p
      run: |
        cp ./bin/opa-plugin  $(go env GOPATH)/bin/opa-plugin
        echo $(go env GOPATH)/bin >> $GITHUB_PATH
      shell: bash

    - name: Generate manifest
      working-directory: c2p
      run: |
        checksum=$(sha256sum "$(go env GOPATH)/bin/opa-plugin" | cut -d ' ' -f 1 )
        cat >  "$(go env GOPATH)/bin/c2p-opa-manifest.json" << EOF
        {
          "metadata": {
            "id": "opa",
            "description": "OPA PVP Plugin",
            "version": "0.0.1",
            "types": [
              "pvp"
            ]
          },
          "executablePath": "opa-plugin",
          "sha256": "$checksum",
          "configuration": [
            {
              "name": "policy-templates",
              "description": "A directory where Rego policies are located.",
              "required": true
            },
            {
              "name": "policy-output",
              "description": "A directory to write OPA configuration data in JSON for checks.",
              "required": false,
              "default": "config.json"
            },
            {
              "name": "policy-results",
              "description": "A directory where OPA results are located.",
              "required": true
            },
            {
              "name": "bundle",
              "description": "A location for an opa policy bundle. If unset, no bundle is created.",
              "required": false
            },
            {
              "name": "bundle-revision",
              "description": "A bundle revision if a bundle is created.",
              "required": false,
              "default": "1.0"
            }
          ]
        }
        EOF
      shell: bash
