plugins:
  opa:
    policy-templates: ./policy-templates/opa
    policy-output: ./policies/opa
    policy-results: ./policy-results/opa
    bundle: my-compliance-bundle.tar.gz
    bundle-revision: {{ RUNID }}
  kyverno:
    policy-dir: ./policy-templates/kyverno
    policy-results-dir: ./policy-results/kyverno
    temp-dir: /tmp
    output-dir: ./policies/kyverno