name: "Run Checks"
description: "Run directory checks in the GitHub Repository"

runs:
  using: "composite"
  steps:
    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Setup ORAS CLI
      uses: oras-project/setup-oras@8d34698a59f5ffe24821f0b48ab62a3de8b64b20 # v1.2.3

    - name: "Run Analysis"
      uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
      with:
        results_file: input.json
        results_format: json

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Install EC
      shell: bash
      run: |
        curl -sLO https://github.com/conforma/cli/releases/download/snapshot/ec_linux_amd64
        chmod +x ec_linux_amd64
        
    - name: Run EC Validate for github_branch_protection
      id: ec_validate_branch_protection
      continue-on-error: true
      shell: bash
      run: |
        ./ec_linux_amd64 validate input --policy "policy-github_branch_protection.yaml" --file input.json --output json=policy-results/opa/github_branch_protection.json
        
    - name: Run EC Validate for scorecard_code_review
      id: ec_validate_code_review
      continue-on-error: true
      shell: bash
      run: |
        ./ec_linux_amd64 validate input --policy "policy-scorecard_code_review.yaml" --file input.json --output json=policy-results/opa/scorecard_code_review.json
  
