name: Evaluate

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - component-definitions/**
      - policy-templates/**

permissions: {}

jobs:
  generate-posture:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup c2pcli
        uses: jpower432/c2p-actions/actions/setup-c2pcli@HEAD

      - name: Install C2P plugins
        uses: ./.github/actions/install-opa-plugin

      - name: Add GitHub RunID to revision
        run: |
          sed -i "s/{{ RUNID }}/${{ github.run_id }}/g" configs/c2p-config.yaml

      - name: Generate policy bundle
        run: c2pcli oscal2policy -c configs/c2p-config.yaml -d component-definitions/component-definition.json -n nist_800_53 -p $(go env GOPATH)/bin

      - uses: actions/upload-artifact@v4
        with:
          name: policy-bundle
          path: my-compliance-bundle.tar.gz

      - uses: ./.github/actions/run-checks

      - name: Aggregate component results
        run: c2pcli result2oscal -c configs/c2p-config.yaml -d component-definitions/component-definition.json -n nist_800_53 -p $(go env GOPATH)/bin

      # Post summary on GitHub action summary
      - name: Summary
        run: |
          wget https://raw.githubusercontent.com/usnistgov/oscal-content/release-v1.0.5-update/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json -O catalog.json
          c2pcli oscal2posture -c configs/c2p-config.yaml -r assessment-results.json -d component-definitions/component-definition.json -n nist_800_53 --catalog catalog.json >> $GITHUB_STEP_SUMMARY